version: '2'

services:

  biotooop:
    container_name: biotooop
    build: .
    environment:
      DB_HOST: mysql
      DB_PASSWORD: example
    depends_on:
      - mysql
    ports:
      - 8080:8080

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: biotooop
    volumes_from:
      - mysql-data

  mysql-data:
    container_name: mysql-data
    image: busybox
    volumes:
      - /var/lib/mysql
